### PR TITLE
Make gh pages friendly

### PR DESCRIPTION
**Pull request by perliedman**
I have removed the empty `Leaflet.gl` directory, which I think is what prevented Github from publishing, for some reason.

I also renamed `slides.html` to `index.html`, to make the URL a bit easier.

Also includes a link to the published slides from the `README.md`.

Great slides, BTW! :)

### CODE REVIEW

**Comment by perliedman** [comment]
You can also have a look at the published result on my site: http://www.liedman.net/leaflet-vs-openlayers-slides/#/

**Comment by IvanSanchez** [comment]
But... the Leaflet.gl files are needed for some slide near the end: https://github.com/IvanSanchez/leaflet-vs-openlayers-slides/blob/gh-pages/slides.html#L993

It should be possible to just link to the Leaflet.gl github pages and fix everything :-)

**Comment by perliedman** [comment]
Ah, ok. When I cloned the repo, `Leaflet.gl` was just an empty directory... is it supposed to be a submodule?

**Comment by IvanSanchez** [comment]
@perliedman Yeah. I think. I always have problems telling submodules apart from subtrees apart from subrepos or whatever. :-)

**Pull request merged**
